### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by timeshift-ted** [chargebee/chargebee-flutter#71]
Crashlytics is reporting this crash is happening regularly:

Fatal Exception: java.lang.IllegalStateException
Reply already submitted
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:268)
com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.error (ChargebeeFlutterSdkPlugin.kt:530)
com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.onError (ChargebeeFlutterSdkPlugin.kt:511)
com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.access$onError (ChargebeeFlutterSdkPlugin.kt:26)
com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin$retrieveProducts$1.onError (ChargebeeFlutterSdkPlugin.kt:159)
com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke (BillingClientManager.kt:51)
com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke (BillingClientManager.kt:21)
com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke (BillingClientManager.kt:69)
com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke (BillingClientManager.kt:21)
com.chargebee.android.billingservice.BillingClientManager$createBillingClientStateListener$1.onBillingServiceDisconnected (BillingClientManager.kt:504)
com.android.billingclient.api.zzaf.onServiceDisconnected (com.android.billingclient:billing@@4.0.0:4)
android.app.LoadedApk$ServiceDispatcher.doDeath (LoadedApk.java:1967)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1982)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7356)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)

**Comment by cb-amutha** [comment]
thanks @timeshift-ted for sharing the logs here.
As per the crash analytics logs, we could see the issue is while fetching the products from google store and unfortunately the app was unable to connect with google play billing service.
Could you please add the test account of google play store and try again. Thanks.

And also, will try to replicate the same issue in our example app and update it.

**Comment by timeshift-ted** [comment]
Hi,

Can you please give me instructions on "add the test account of google play
store"?

Ted Johnson
Timeshift Media, Inc.

**Comment by nikolashaag** [comment]
Hi @cb-amutha ,

we have 120 reports of the same error since going live 1 month ago. Also through Crashlytics.


What causes the failure to connect to Google Play services here?

**Comment by ciriousjoker** [comment]
We also have this issue, but it's unclear why. I have a suspicion it's caused by the new default proguard rules in combination with a perhaps swallowed error, but I have no proof.

**Comment by ciriousjoker** [comment]
Here's our stacktrace:

> Fatal Exception: java.lang.IllegalStateException: Reply already submitted
>        at bh.c$g.a(SourceFile:1)
>        at lh.k$a$a.b(SourceFile:1)
>        at b4.b.f(SourceFile:1)
>        at b4.b.h(SourceFile:1)
>        at b4.b.b(SourceFile:1)
>        at b4.b$i.onError(SourceFile:1)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:2)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:1)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:2)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:1)
>        at com.chargebee.android.billingservice.BillingClientManager$createBillingClientStateListener$1.onBillingServiceDisconnected(:15)
>        at u2.v.onServiceDisconnected(SourceFile:1)
>        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2382)
>        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2397)
>        at android.os.Handler.handleCallback(Handler.java:942)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8762)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Interestingly, the underlying error message is this:



> **flutter_error_exception** | PlatformException(502, java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType, java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType, null)
> **flutter_error_reason** | thrown purchase() failed.

This suggests missing proguard rules.
We're using `chargebee_flutter: v0.2.1`.

- Perhaps you guys are using an old version of retrofit? This seems related: https://github.com/square/retrofit/issues/3751

**Comment by ciriousjoker** [comment]
Issue is also reproducible in v0.3.0... this is affecting our production users who can't do purchases, please fix this asap.

**Comment by ciriousjoker** [comment]
Here are reproduction steps:

1. Open Play Store
2. Open the own app
3. Open random other app
4. Close Play Store
5. Switch back to the app (it crashed)

Basically, closing the Play Store crashes the app if it's in the background. If it's in the foreground, nothing happens.

**Comment by cb-haripriyan** [comment]
Thanks for the steps to reproduce @ciriousjoker 
We are looking into this and will update here about the progress.

**Comment by ciriousjoker** [comment]
@cb-haripriyan Any news?

**Comment by cb-haripriyan** [comment]
We have identified the underlying case which was causing the multiple call backs. The Billing Library calls the listeners multiple times during disconnection/reconnection, which in turns causes multiple callbacks on Flutter. We are working on a method to avoid this.

**Comment by ciriousjoker** [comment]
@cb-haripriyan Any eta for this? This is severely affecting our users.

**Comment by cb-haripriyan** [comment]
@ciriousjoker We are targeting this for early next week.

**Comment by cb-haripriyan** [comment]
@ciriousjoker We are expecting to release a fix by utmost tomorrow. 
Apologies, we were delayed due to unforeseen circumstances.

**Comment by cb-haripriyan** [comment]
@ciriousjoker @timeshift-ted 
This should be fixed in the version [0.4.1](https://github.com/chargebee/chargebee-flutter/releases/tag/v0.4.1). Can you please check and confirm?

**Comment by ciriousjoker** [comment]
@cb-haripriyan This doesn't seem to happen nearly as often anymore as this one, but apparently it still exists in `v1.0.0-beta.2`.

### Stacktrace

```log
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at lh.c$g.a(SourceFile:1)
       at uh.k$a$a.b(SourceFile:1)
       at h4.b.f(SourceFile:1)
       at h4.b.g(SourceFile:1)
       at h4.b.b(SourceFile:1)
       at h4.b$i.onError(SourceFile:1)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:2)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:1)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:2)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:1)
       at com.chargebee.android.billingservice.BillingClientManager$createBillingClientStateListener$1.onBillingServiceDisconnected(:15)
       at c3.u.onServiceDisconnected(SourceFile:1)
       at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2226)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2241)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

Perhaps this happens if a user signs into or out of the Play Store while the app is running?

**Comment by cb-haripriyan** [comment]
@ciriousjoker Missed updating it here. The version v1.0.0-beta.4 includes the fix for this.

**Comment by ciriousjoker** [comment]
The fix solved the issue, this can probably be closed for now and reopened if it occurs again
